services:
  # test runner intended to run live tests against targets on public internet
  test-runner-live:
    platform: linux/amd64
    image: ${DOCKER_IMAGE_TEST_RUNNER:-${DOCKER_REGISTRY:-ghcr.io/internetstandards}/test-runner:$RELEASE}
    # don't run anything, just make this container available to run tests in on demand
    command: python3 -m pytest -v integration-tests/live/
    environment:
      - APP_URLS=${APP_URLS:-https://internet.nl}
      - BATCH_API_AUTH
      - TEST_DOMAINS
      - TEST_EMAILS
    networks:
      live-tests:
    volumes:
      - ../:/source

networks:
  live-tests:
    # required to enable IPv6 on Docker Desktop runtime
    enable_ipv6: true
    driver: bridge
    driver_opts:
      # required to enable IPv6 on Colima Docker runtime
      com.docker.network.enable_ipv6: "true"
