services:
  tools:
    platform: linux/amd64
    image: ${DOCKER_IMAGE_tools:-${DOCKER_REGISTRY:-ghcr.io/internetstandards}/tools:${RELEASE:-latest}}

    volumes:
      - ../:/source/
      # make docker available inside the container
      - /var/run/docker.sock:/var/run/docker.sock
